# Generated by Django 2.2.4 on 2019-12-25 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='Zip_code',
            new_name='zip_code',
        ),
    ]
